
version: '3.3'

networks:
  spyssh_network:
    driver: bridge
    ipam: 
      config:
       - subnet: 172.28.0.0/24

services:
  spyssh:
    build: spyssh/.
    container_name: spyssh
    ports:  
      - "6666:22"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 400M
    healthcheck: 
      test: ["CMD", "nc", "-z", "localhost", "6666"] 
      interval: 10s 
      timeout: 10s 
      retries: 3
    networks:
      spyssh_network:
        ipv4_address: 172.28.0.5

    cap_add:
      - SYS_PTRACE


  botssh:
    build: spyssh_bot/.
    container_name: spyssh_bot
    restart: always
    extra_hosts:
      spyssh: 172.28.0.5
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 400M
    networks:
      spyssh_network:
        ipv4_address: 172.28.0.6

  
      